#!/usr/bin/env php
<?php


require __DIR__ . '/vendor/autoload.php';
// require_once  __DIR__ . '/../core/app.php';
use core\Console\Application;

$application = new Application(__DIR__);

// ... register commands / 注册命令
$application->run();
